import Stack from "../stack"

it('should push and pop elements from stack', () => {
  const stack = new Stack<number>()
  expect(stack.top()).toEqual(null)
  expect(stack.size()).toEqual(0)

  stack.push(1)
  expect(stack.top()).toEqual(1)
  expect(stack.size()).toEqual(1)
  stack.push(2)
  stack.push(2)
  stack.push(7)
  expect(stack.top()).toEqual(7)
  expect(stack.size()).toEqual(4)
  const last = stack.pop()
  expect(last).toEqual(7)
  stack.pop()
  stack.pop()
  expect(stack.top()).toEqual(1)
  expect(stack.size()).toEqual(1)
  stack.pop()
  expect(stack.top()).toEqual(null)
  expect(stack.size()).toEqual(0)
  stack.pop()
  stack.pop()
  expect(stack.top()).toEqual(null)
  expect(stack.size()).toEqual(0)
})

